### ISSUE TITLE
How to customize this code to evaluate MOT metrics on custom datasets?

### ISSUE THREAD

**Issue by pvtien96** [dendorferpatrick/MOTChallengeEvalKit#1]
Dear all,
I'm trying to evaluate my custom mot algorithm on my custom datasets.
I've read almost related papers on motchanllenge.net and I was wondering if I can prepare my custom datasets with the same format of groundtruth of Mot (eg. MOT16) and then apply this repositories. But still I've not found the right way to do this.
Any recommendations is appreciated.
Thanks!

**Comment by dendorferpatrick** [comment]
Hi, 
I updated the [Readme](https://github.com/dendorferpatrick/MOTChallengeEvalKit/blob/master/MOT/README.md) and added the section "Evaluating on your own Data". I hope this helps. Let me know if you still have issues.

**Comment by pvtien96** [comment]
Many thanks @dendorferpatrick . Problem solved.
